nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.0.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: '@yarnpkg/plugin-compat'

supportedArchitectures: 
  os:
    - 'darwin'
    - 'linux'
    - 'win32'
  cpu:
    - 'x64'
    - 'x86'
    - 'arm'
    - 'arm64'
    - 'ia32'
  libc:
    - 'glibc'
    - 'musl'