/* tslint:disable */
/* eslint-disable */
/**
 * IFM IO-Link
 * This is an OpenAPI declaration of the available API\'s on [IFM](https://ifm.com) IO-Link Masters. Produced for [The Tech Company](https://github.com/TheTechCompany). For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

