name: Build Apps (HiveCommand)
on:
  push:
    branches:
      - master

jobs: 

  build_server:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push 
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          context: ./packages/app/hivecommand-backend
          file: ./packages/app/hivecommand-backend/Dockerfile
          push: true
          tags: thetechcompany/hivecommand-backend:latest
          build-args: |
            BUILD_ENV=github
  
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  

  build_coreapps:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        apps: [ frontend ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn

      - run: lerna bootstrap --scope @hive-command/${{ matrix.apps }} --include-dependencies

      - run: export REACT_APP_API="https://api.hexhive.io"
      - run: export REACT_APP_URL="https://go.hexhive.io"
      - run: export PUBLIC_PATH="https://apps.hexhive.io/${{matrix.apps}}/"
      
      - name: Build web
        run: (export REACT_APP_URL="https://go.hexhive.io" PUBLIC_PATH="https://apps.hexhive.io/${{matrix.apps}}/" REACT_APP_API="https://api.hexhive.io" NODE_ENV=production CI=false; lerna run build --scope @hive-command/${{ matrix.apps }} --include-dependencies)
      
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      
      - name: Make Bucket URL
        run: echo "BUCKET_URL=S3_${{matrix.apps}}_BUCKET" | tr a-z A-Z >> $GITHUB_ENV

      - name: Upload new web-build
        run: |
          aws s3 sync packages/app/hivecommand-${{ matrix.apps }}/dist/ s3://${{ secrets.APP_BUCKET }}/hivecommand-${{matrix.apps}} --delete

