name: docs

on: 
  push:
    branches: 
      - master
    paths: ["docs/**"]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: tool3/docsify-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}