name: HiveCommand Supporting Infrastructure

on:
  push:
    branches:
      # - staging
      - master
    paths: ["packages/lambdas/**", "packages/infrastructure/lambdas/**"]

concurrency: hivecommand-lambda-infra-${{ github.ref }}

jobs:

  push_mqtt_infra:
    name: Update Pulumi Infra
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: echo "IMAGE_TAG=sha-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ap-southeast-2
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: yarn install --frozen-lockfile
        working-directory: ./packages/infrastructure/lambdas

      - name: Setup stack
        run: |
          echo "STACK_NAME=ultraviolet/hivecommand-lambdas/lambdas-prod" >> $GITHUB_ENV      
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Build export-lambda
        run: npx lerna run build --scope @hive-command/schematic-export --include-dependencies
        env:
          CI: false

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: zip -qq -r ../../infrastructure/lambdas/src/export-lambda/archive.zip * -x "*/@hive-command/export-page/node_modules/*"
        working-directory: packages/lambdas/export-schematic

      - name: Update infrastructure
        uses: pulumi/actions@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          command: up
          stack-name: ${{env.STACK_NAME}}
          work-dir: ./packages/infrastructure/lambdas
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
