name: Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Use NodeJS 16"
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        yarn
        npx lerna bootstrap --no-ci

        npx lerna run build --no-private

    - name: Run tests # Run tests of all packages
      run: npx lerna exec 'npm run test --forceExit'
